"""initial

Revision ID: 9251995c7b1e
Revises: 
Create Date: 2024-06-07 10:43:33.020162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9251995c7b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
